name: "ðŸ› Bug Report"
description: "Create a report to help us improve the plugin."
labels: [ "bug" ]

assignees:
  - ryderbelserion

body:
  - type: markdown
    attributes:
      value: |
        Note: Search to see if an issue already exists for the bug you are reporting.

        Add any gif / imgur links if need be. Markdown is supported!

        If you have any large stack traces / errors, Please use https://mclo.gs/

        Spark > https://spark.lucko.me/download
  - type: input
    attributes:
      label: Spark link
      description: We ask that Spark profile are shared through a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.
      placeholder: Output of /spark profiler --timeout 300
    validations:
      required: false
  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      description: Type /version plugin-name in-game
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Server Version
      description: What server version are you on?
      options:
        - "1.21.1"
        - "1.21.2"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Server Platform
      description: What server platform are you using?
      options:
        - Paper
        - Purpur
        - Folia
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Change value in placeholder.yml '...'
        3. Run command '...'
        4. See error
    validations:
      required: true
